# Stage 1: Build Flutter Web dùng Image có sẵn cho nhẹ
FROM ghcr.io/cirruslabs/flutter:stable AS build-env

WORKDIR /app
# Copy pubspec trước để cache layer (tăng tốc build)
COPY pubspec.* ./
RUN flutter pub get

# Copy toàn bộ code và build
COPY . .
RUN flutter build web --release

# Stage 2: Serve with Nginx
FROM nginx:alpine
# Copy kết quả build vào thư mục của Nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html

# KHÔNG DÙNG EXPOSE 80 (Render tự quản lý port)

# Lệnh khởi chạy Nginx và ép nó nghe theo biến $PORT của Render
CMD ["sh", "-c", "sed -i 's/listen 80;/listen '\"$PORT\"';/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]